### ISSUE TITLE
Create exit DAO guide 

### ISSUE THREAD

**Issue by 0xean** [elasticdao/docs#2]
- screenshots from exit module
- explanation on exit amount, etc.

**Comment by 0xean** [comment]
@smalldutta - did I miss the gist link here or what is the status of this guide?

**Comment by 0xSSDD** [comment]
Currently a WIP: https://app.gitbook.com/@elasticdao/s/docs/guides/exit-the-dao

**Comment by 0xSSDD** [comment]
The finished version, available for review: https://docs.elasticdao.org/guides/exit-the-dao
